#pragma once
namespace Toshi
{
	class TRenderParamTable
	{
		enum V4PARAM
		{
			V4PARAM_AMBIENTCOLOUR = 1,
			V4PARAM_DIRLIGHT0,
			V4PARAM_DIRLIGHT1,
			V4PARAM_DIRLIGHT2,
			V4PARAM_DIRLIGHT0COLOUR,
			V4PARAM_DIRLIGHT1COLOUR,
			V4PARAM_DIRLIGHT2COLOUR,
			V4PARAM_EYEPOSMS,
			V4PARAM_LIGHTSCOUNTS,
			V4PARAM_POINTLIGHT0,
			V4PARAM_POINTLIGHT0COLOUR,
			V4PARAM_POINTLIGHT0PARAMS,
			V4PARAM_POINTLIGHT1,
			V4PARAM_POINTLIGHT1COLOUR,
			V4PARAM_POINTLIGHT1PARAMS,
			V4PARAM_POINTLIGHT2,
			V4PARAM_POINTLIGHT2COLOUR,
			V4PARAM_POINTLIGHT2PARAMS,
			V4PARAM_POINTLIGHT3,
			V4PARAM_POINTLIGHT3COLOUR,
			V4PARAM_POINTLIGHT3PARAMS,
			V4PARAM_SHADOWLIGHTDIR0,
			V4PARAM_SPOTLIGHT0,
			V4PARAM_SPOTLIGHT0COLOUR,
			V4PARAM_SPOTLIGHT0DIR,
			V4PARAM_SPOTLIGHT0PARAMS,
			V4PARAM_SPOTLIGHT1,
			V4PARAM_SPOTLIGHT1COLOUR,
			V4PARAM_SPOTLIGHT1DIR,
			V4PARAM_SPOTLIGHT1PARAMS
		};

		enum M44PARAM
		{
			M44PARAM_MODELVIEW = 1,
			M44PARAM_MODELVIEWPROJ,
			M44PARAM_MODELWORLD,
			M44PARAM_PROJ
		};

		enum TEXPARAM
		{
			TEXPARAM_CUBEENVMAP = 1,
			TEXPARAM_FRAMEBUF,
			TEXPARAM_LIGHTFALLOFF,
			TEXPARAM_PLANARENVMAP,
			TEXPARAM_SHADOWTEX
		};

		int m_iNumV4Params;		// 0x24
		int m_iNumMatrixParams; // 0x28
		int m_iNumTexParams;	// 0x2C
	};
}