#pragma once

TOSHI_NAMESPACE_START

namespace TCollisionCommon
{

enum TOSHICGROUP
{
	TOSHICGROUP_DEFAULT = -1,
	TOSHICGROUP_SUPPORT,
	TOSHICGROUP_PLAYER,
	TOSHICGROUP_RACCOONS,
	TOSHICGROUP_GRASS,
	TOSHICGROUP_TIN,
	TOSHICGROUP_TIMBER,
	TOSHICGROUP_STONE,
	TOSHICGROUP_DIRT,
	TOSHICGROUP_WATER,
	TOSHICGROUP_SAND,
	TOSHICGROUP_MUD,
	TOSHICGROUP_HAY,
	TOSHICGROUP_WOOD,
	TOSHICGROUP_UNKNOWN,
	TOSHICGROUP_NOFRICTION,
	TOSHICGROUP_LIQUID,
	TOSHICGROUP_WATERWALL,
	TOSHICGROUP_DEEPWATER,
	TOSHICGROUP_WATER2,
	TOSHICGROUP_CAMERA,
	TOSHICGROUP_NUMOF
};

} // namespace TCollisionCommon

TOSHI_NAMESPACE_END
