#pragma once

TOSHI_NAMESPACE_START

namespace TCollisionCommon
{

enum TOSHICGROUP
{
	TOSHICGROUP_DEFAULT = -1,
	TOSHICGROUP_SUPPORT,
	TOSHICGROUP_PLAYER,
	TOSHICGROUP_RACCOONS,
	TOSHICGROUP_GRASS,
	TOSHICGROUP_TIN,
	TOSHICGROUP_TIMBER,
	TOSHICGROUP_STONE,
	TOSHICGROUP_DIRT,
	TOSHICGROUP_WATER,
	TOSHICGROUP_SAND,
	TOSHICGROUP_MUD,
	TOSHICGROUP_HAY,
	TOSHICGROUP_WOOD,
	TOSHICGROUP_UNKNOWN,
	TOSHICGROUP_NOFRICTION,
	TOSHICGROUP_LIQUID,
	TOSHICGROUP_WATERWALL,
	TOSHICGROUP_DEEPWATER,
	TOSHICGROUP_WATER2,
	TOSHICGROUP_CAMERA,
	TOSHICGROUP_NUMOF
};

using TOSHICGROUPFLAG = TUINT32;
enum TOSHICGROUPFLAG_ : TOSHICGROUPFLAG
{
	TOSHICGROUPFLAG_NONE       = 0,
	TOSHICGROUPFLAG_SUPPORT    = BITFLAG( TOSHICGROUP_SUPPORT ),
	TOSHICGROUPFLAG_PLAYER     = BITFLAG( TOSHICGROUP_PLAYER ),
	TOSHICGROUPFLAG_RACCOONS   = BITFLAG( TOSHICGROUP_RACCOONS ),
	TOSHICGROUPFLAG_GRASS      = BITFLAG( TOSHICGROUP_GRASS ),
	TOSHICGROUPFLAG_TIN        = BITFLAG( TOSHICGROUP_TIN ),
	TOSHICGROUPFLAG_TIMBER     = BITFLAG( TOSHICGROUP_TIMBER ),
	TOSHICGROUPFLAG_STONE      = BITFLAG( TOSHICGROUP_STONE ),
	TOSHICGROUPFLAG_DIRT       = BITFLAG( TOSHICGROUP_DIRT ),
	TOSHICGROUPFLAG_WATER      = BITFLAG( TOSHICGROUP_WATER ),
	TOSHICGROUPFLAG_SAND       = BITFLAG( TOSHICGROUP_SAND ),
	TOSHICGROUPFLAG_MUD        = BITFLAG( TOSHICGROUP_MUD ),
	TOSHICGROUPFLAG_HAY        = BITFLAG( TOSHICGROUP_HAY ),
	TOSHICGROUPFLAG_WOOD       = BITFLAG( TOSHICGROUP_WOOD ),
	TOSHICGROUPFLAG_UNKNOWN    = BITFLAG( TOSHICGROUP_UNKNOWN ),
	TOSHICGROUPFLAG_NOFRICTION = BITFLAG( TOSHICGROUP_NOFRICTION ),
	TOSHICGROUPFLAG_LIQUID     = BITFLAG( TOSHICGROUP_LIQUID ),
	TOSHICGROUPFLAG_WATERWALL  = BITFLAG( TOSHICGROUP_WATERWALL ),
	TOSHICGROUPFLAG_DEEPWATER  = BITFLAG( TOSHICGROUP_DEEPWATER ),
	TOSHICGROUPFLAG_WATER2     = BITFLAG( TOSHICGROUP_WATER2 ),
	TOSHICGROUPFLAG_CAMERA     = BITFLAG( TOSHICGROUP_CAMERA ),
	TOSHICGROUPFLAG_ALL        = 0xFFFFFFFF
};

} // namespace TCollisionCommon

TOSHI_NAMESPACE_END
