#pragma once

TOSHI_NAMESPACE_START

class TFileLexer
{
public:
	enum TOKEN
	{
		TOKEN_EOF,
		TOKEN_SEMI,
		TOKEN_COLON,
		TOKEN_COMMA,
		TOKEN_DOT,
		TOKEN_UNK,
		TOKEN_DOLLAR,
		TOKEN_OPENSQR,
		TOKEN_CLOSESQR,
		TOKEN_OPENBRACE,
		TOKEN_CLOSEBRACE,
		TOKEN_OPENPAREN,
		TOKEN_CLOSEPAREN,
		TOKEN_LESSTHAN,
		TOKEN_GREATERTHAN,
		TOKEN_EQUAL,
		TOKEN_EXCLAMATION,
		TOKEN_HYPHEN,
		TOKEN_IDENT,
		TOKEN_STRING,
		TOKEN_INTEGER,
		TOKEN_UINTEGER,
		TOKEN_FLOAT,
		TOKEN_COMMENT,
		TOKEN_INCLUDE,
		TOKEN_NUMOF
	};

	static const TCHAR* GetTokenName( TOKEN a_eToken );
};

TOSHI_NAMESPACE_END
